apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: lyrical-impact-tags
      jib:
        project: applications/tags-server
        type: maven
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml