apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: gcr.io/lyrical-impact/li/impacted-server
      jib:
        project: applications/impacted-server
    - image: gcr.io/lyrical-impact/li/lookup-server
      jib:
        project: applications/lookup-server
    - image: gcr.io/lyrical-impact/li/mvc-server
      jib:
        project: applications/mvc-server
    - image: gcr.io/lyrical-impact/li/tags-server
      jib:
        project: applications/tags-server
    - image: gcr.io/lyrical-impact/li/verses-server
      jib:
        project: applications/verses-server
    - image: gcr.io/lyrical-impact/li/eureka
      jib:
        project: platform-services/eureka
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
      - k8s/*.yaml
