apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: li/impacted-server
      jib:
        project: applications/impacted-server
    - image: li/lookup-server
      jib:
        project: applications/lookup-server
    - image: li/mvc-server
      jib:
        project: applications/mvc-server
    - image: li/tags-server
      jib:
        project: applications/tags-server
    - image: li/verses-server
      jib:
        project: applications/verses-server
    - image: li/eureka
      jib:
        project: platform-services/eureka
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
      - k8s/*.yaml
