apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-base
  labels:
    app: lyrical-impact
data:
  SPRING_PROFILES_ACTIVE: k8s
  EUREKA_URI: http://eureka-service:8761/eureka
  KEYCLOAK_REDIRECT_HOST_PORT: http://lyricalimpact.net:9090
  KEYCLOAK_HOST_PORT: http://keycloak.net:8080
