apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-db
  labels:
    app: lyrical-impact
data:
  MYSQL_DATABASE: lyrical
  mariadb.cnf: |
    [client]
    default-character-set = utf8
    [mysqld]
    character-set-server  = utf8
    collation-server      = utf8_unicode_ci
