apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: lyrical-impact
spec:
  ports:
    - protocol: TCP
      port: 3306
  selector:
    app: lyrical-impact
    tier: db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: lyrical-impact
spec:
  selector:
    matchLabels:
      app: lyrical-impact
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5.1
          envFrom:
            - configMapRef:
                name: configmap-db
            - secretRef:
                name: secret-db
          ports:
            - name: mariadb
              containerPort: 3306
