apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: lyrical-impact
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30306
  selector:
    app: lyrical-impact
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: lyrical-impact
spec:
  selector:
    matchLabels:
      app: lyrical-impact
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5.2
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: configmap-db
            - secretRef:
                name: secret-db
          volumeMounts:
            - name: mariadb-conf-d-volume
              mountPath: /etc/mysql/mariadb.conf.d/mariadb.cnf
              subPath: mariadb.cnf
          ports:
            - name: mariadb
              containerPort: 3306
      volumes:
        - name: mariadb-conf-d-volume
          configMap:
            name: configmap-db
            items:
              - path: "mariadb.cnf"
                key: mariadb.cnf
