apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8761
      nodePort: 32327
  selector:
    app: lyrical-impact
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
    spec:
      containers:
        - name: lyrical-impact-eureka-pod
          image: li/eureka
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8761
