apiVersion: v1
kind: Service
metadata:
  name: impacted-service
  labels:
    app: lyrical-impact
spec:
  ports:
    - protocol: TCP
      port: 8383
  selector:
    app: lyrical-impact
    tier: impacted
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: impacted-service
  labels:
    app: lyrical-impact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: impacted
    spec:
      containers:
        - name: lyrical-impact-impacted-pod
          image: li/impacted-server
          imagePullPolicy: Never
          env:
            - name: EUREKA_URI
              value: http://eureka-service:8761/eureka
          ports:
            - name: http
              containerPort: 8383
