apiVersion: v1
kind: Service
metadata:
  name: impacted-service
spec:
  ports:
    - protocol: TCP
      port: 8383
  selector:
    app: lyrical-impact
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: impacted-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
    spec:
      containers:
        - name: lyrical-impact-impacted-pod
          image: li/impacted-server
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8383
