apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: lyrical-impact
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.78.119
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
      targetPort: 8080
  selector:
    app: lyrical-impact
    tier: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: lyrical-impact
spec:
  selector:
    matchLabels:
      app: lyrical-impact
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: auth
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:9.0.0
          envFrom:
            - configMapRef:
                name: configmap-keycloak
            - secretRef:
                name: secret-keycloak
          volumeMounts:
            - name: keycloak-import-volume
              mountPath: /tmp/keycloak-lyrical-realm.json
              subPath: keycloak-lyrical-realm.json
          ports:
            - name: keycloak
              containerPort: 8080
      volumes:
        - name: keycloak-import-volume
          configMap:
            name: configmap-keycloak-import
