apiVersion: v1
kind: Service
metadata:
  name: mvc-service
  labels:
    app: lyrical-impact
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8443
      nodePort: 30443
      name: https
  selector:
    app: lyrical-impact
    tier: mvc
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-service
  labels:
    app: lyrical-impact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: mvc
    spec:
      containers:
        - name: lyrical-impact-mvc-pod
          image: li/mvc-server
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: configmap-base
            - secretRef:
                name: secret-mvc
          ports:
            - name: http
              containerPort: 8443
