apiVersion: v1
kind: Service
metadata:
  name: mvc-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32320
  selector:
    app: lyrical-impact
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
    spec:
      containers:
        - name: lyrical-impact-mvc-pod
          image: li/mvc-server
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
