apiVersion: v1
kind: Service
metadata:
  name: tags-service
  labels:
    app: lyrical-impact
spec:
  ports:
    - protocol: TCP
      port: 8181
  selector:
    app: lyrical-impact
    tier: tags
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags-service
  labels:
    app: lyrical-impact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: tags
    spec:
      containers:
        - name: lyrical-impact-tags-pod
          image: li/tags-server
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: configmap-base
            - configMapRef:
                name: configmap-db-app
            - secretRef:
                name: secret-db-app
          ports:
            - name: http
              containerPort: 8181
