apiVersion: v1
kind: Service
metadata:
  name: verses-service
  labels:
    app: lyrical-impact
spec:
  ports:
    - protocol: TCP
      port: 8282
  selector:
    app: lyrical-impact
    tier: verses
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verses-service
  labels:
    app: lyrical-impact
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: verses
    spec:
      containers:
        - name: lyrical-impact-verses-pod
          image: li/verses-server
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: configmap-base
            - configMapRef:
                name: configmap-db-app
            - secretRef:
                name: secret-db-app
          ports:
            - name: http
              containerPort: 8282
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: 8282
