apiVersion: v1
kind: Service
metadata:
  name: verses-service
  labels:
    app: lyrical-impact
spec:
  ports:
    - protocol: TCP
      port: 8282
  selector:
    app: lyrical-impact
    tier: verses
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verses-service
  labels:
    app: lyrical-impact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: verses
    spec:
      containers:
        - name: lyrical-impact-verses-pod
          image: li/verses-server
          imagePullPolicy: Never
          env:
            - name: EUREKA_URI
              value: http://eureka-service:8761/eureka
          ports:
            - name: http
              containerPort: 8282
