version: "2.4"
services:
  app:
    build: .
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    env_file:
      - secrets-app.env 
    ports:
      - "8080:8080"
    depends_on:
      - tags
      - eureka
      - db
  tags:
    build: ..\lyrical-impact-tags
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    ports:
      - "8181:8181"
    depends_on:
      - eureka      
  eureka:
    build: ..\lyrical-impact-eureka
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "8761:8761"
  db:
    image: mariadb:10.4
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: lyricalimpact
    env_file:
      - secrets-db.env 
    ports:
      - "3306:3306"
