version: "2.4"
#
# Use: Fast developer stack deployment
# - Runs with local directory Dockerfiles and in-memory H2 database services
#
services:
  app:
    image: dev/lyrical-impact/li/mvc-server:2.0-SNAPSHOT
    build:
      context: ../applications/mvc-server
      args:
        - JAR_FILE=target/lyrical-impact-mvc-2.0-SNAPSHOT.jar
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
      - KEYCLOAK_HOST_PORT=http://keycloak.lyricalimpact.net:8080
    env_file:
      - secrets-app.env
    expose:
      - "9090"
    ports:
      - "9090:9090"
    networks:
      - appnet
    depends_on:
      - tags
      - verses
      - impacted
      - lookup
      - eureka
  tags:
    image: dev/lyrical-impact/li/tags-server:2.0-SNAPSHOT
    build:
      context: ../applications/tags-server
      args:
        - JAR_FILE=target/lyrical-impact-tags-2.0-SNAPSHOT.jar
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8181"
    ports:
      - "8181:8181"
    networks:
      - appnet
    depends_on:
      - eureka
  verses:
    image: dev/lyrical-impact/li/verses-server:2.0-SNAPSHOT
    build:
      context: ../applications/verses-server
      args:
        - JAR_FILE=target/lyrical-impact-verses-2.0-SNAPSHOT.jar
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8282"
    ports:
      - "8282:8282"
    networks:
      - appnet
    depends_on:
      - eureka
  impacted:
    image: dev/lyrical-impact/li/impacted-server:2.0-SNAPSHOT
    build:
      context: ../applications/impacted-server
      args:
        - JAR_FILE=target/lyrical-impact-impacted-2.0-SNAPSHOT.jar
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8383"
    ports:
      - "8383:8383"
    networks:
      - appnet
    depends_on:
      - eureka
  lookup:
    image: dev/lyrical-impact/li/lookup-server:2.0-SNAPSHOT
    build:
      context: ../applications/lookup-server
      args:
        - JAR_FILE=target/lyrical-impact-lookup-2.0-SNAPSHOT.jar
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8484"
    ports:
      - "8484:8484"
    networks:
      - appnet
    depends_on:
      - eureka
  eureka:
    image: dev/lyrical-impact/li/eureka:2.0-SNAPSHOT
    build:
      context: ../platform-services/eureka
      args:
        - JAR_FILE=target/lyrical-impact-eureka-2.0-SNAPSHOT.jar
    mem_limit: 256m
    mem_reservation: 256m
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - appnet
  keycloak:
    image: jboss/keycloak:11.0.3
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/keycloak-lyrical-realm.json
    env_file:
      - secrets-keycloak.env
    volumes:
      - "./vols/keycloak-lyrical-realm.json:/tmp/keycloak-lyrical-realm.json:ro"
    mem_limit: 512m
    mem_reservation: 512m
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - keycloaknet
networks:
  appnet:
    driver: bridge
  keycloaknet:
    driver: bridge
