version: "2.4"
services:
  app:
    build:
      context: ../applications/mvc-server
      args:
        - JAR_FILE=target/lyrical-impact-mvc-1.0-SNAPSHOT.jar
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
      - KEYCLOAK_HOST_PORT=http://192.168.1.107:8080
    env_file:
      - secrets-app.env
    expose:
      - "9090"
    ports:
      - "9090:9090"
    networks:
      - appnet
    depends_on:
      - tags
      - verses
      - impacted
      - lookup
      - eureka
  tags:
    build:
      context: ../applications/tags-server
      args:
        - JAR_FILE=target/lyrical-impact-tags-1.0-SNAPSHOT.jar
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8181"
    ports:
      - "8181:8181"
    networks:
      - appnet
    depends_on:
      - eureka
  verses:
    build:
      context: ../applications/verses-server
      args:
        - JAR_FILE=target/lyrical-impact-verses-1.0-SNAPSHOT.jar
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8282"
    ports:
      - "8282:8282"
    networks:
      - appnet
    depends_on:
      - eureka
  impacted:
    build:
      context: ../applications/impacted-server
      args:
        - JAR_FILE=target/lyrical-impact-impacted-1.0-SNAPSHOT.jar
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8383"
    ports:
      - "8383:8383"
    networks:
      - appnet
    depends_on:
      - eureka
  lookup:
    build:
      context: ../applications/lookup-server
      args:
        - JAR_FILE=target/lyrical-impact-lookup-1.0-SNAPSHOT.jar
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8484"
    ports:
      - "8484:8484"
    networks:
      - appnet
    depends_on:
      - eureka
  eureka:
    build:
      context: ../platform-services/eureka
      args:
        - JAR_FILE=target/lyrical-impact-eureka-1.0-SNAPSHOT.jar
    mem_limit: 256m
    mem_reservation: 256m
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - appnet
  keycloak:
    image: jboss/keycloak:9.0.2
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/keycloak-lyrical-realm.json
    env_file:
      - secrets-keycloak.env
    volumes:
      - "./vols/keycloak-lyrical-realm.json:/tmp/keycloak-lyrical-realm.json:ro"
    mem_limit: 512m
    mem_reservation: 512m
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - keycloaknet
networks:
  appnet:
    driver: bridge
  keycloaknet:
    driver: bridge
