version: "2.4"
services:
  app:
    image: lyrical-impact-mvc:0.9-SNAPSHOT
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    env_file:
      - secrets-app.env
    ports:
      - "8443:8443"
    depends_on:
      - tags
      - verses
      - impacted
      - eureka
      - db
  tags:
    image: lyrical-impact-tags:0.9-SNAPSHOT
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    depends_on:
      - eureka
  verses:
    image: lyrical-impact-verses:0.9-SNAPSHOT
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    depends_on:
      - eureka
  impacted:
    image: lyrical-impact-impacted:0.9-SNAPSHOT
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    depends_on:
      - eureka
  lookup:
    image: lyrical-impact-lookup:0.9-SNAPSHOT
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
    depends_on:
      - eureka
  eureka:
    image: lyrical-impact-eureka:0.9-SNAPSHOT
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "8761:8761"
  db:
    image: mariadb:10.4
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=lyricalimpact
    env_file:
      - secrets-db.env
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "3306:3306"
  keycloak:
    image: jboss/keycloak:9.0.0
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/keycloak-lyrical-realm.json
    env_file:
      - secrets-keycloak.env
    volumes:
      - "./keycloak-lyrical-realm.json:/tmp/keycloak-lyrical-realm.json:ro"
    mem_limit: 512m
    mem_reservation: 512m
    ports:
      - "9090:8080"
