version: "2.4"
services:
  app:
    image: li/mvc-server:latest
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URI=http://eureka:8761/eureka
    env_file:
      - secrets-app.env
    ports:
      - "8443:8443"
    depends_on:
      - tags
      - verses
      - impacted
      - lookup
      - eureka
      - keycloak
  tags:
    image: li/tags-server:latest
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URI=http://eureka:8761/eureka
    depends_on:
      - db
      - eureka
  verses:
    image: li/verses-server:latest
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URI=http://eureka:8761/eureka
    depends_on:
      - db
      - eureka
  impacted:
    image: li/impacted-server:latest
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URI=http://eureka:8761/eureka
    depends_on:
      - db
      - eureka
  lookup:
    image: li/lookup-server:latest
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URI=http://eureka:8761/eureka
    depends_on:
      - eureka
  eureka:
    image: li/eureka:latest
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "8761:8761"
  db:
    image: mariadb:10.5.1
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=lyrical
    env_file:
      - secrets-db.env
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "3306:3306"
  keycloak:
    image: jboss/keycloak:9.0.0
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/keycloak-lyrical-realm.json
    env_file:
      - secrets-keycloak.env
    volumes:
      - "./vols/keycloak-lyrical-realm.json:/tmp/keycloak-lyrical-realm.json:ro"
    mem_limit: 512m
    mem_reservation: 512m
    ports:
      - "9090:8080"
