version: "2.4"
services:
  app:
    image: li/mvc-server:latest
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - EUREKA_URI=http://eureka:8761/eureka
      - KEYCLOAK_HOST_PORT=http://192.168.1.103:8080
#      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:61000
    env_file:
      - secrets-app.env
    expose:
      - "9090"
    ports:
      - "9090:9090"
#      - "61000:61000"
    networks:
      - appnet
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9090"]
    depends_on:
      - tags
      - verses
      - impacted
      - lookup
      - eureka
  tags:
    image: li/tags-server:latest
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - LYRICAL_MYSQL_URI=jdbc:mariadb://db:3306/lyrical
      - EUREKA_URI=http://eureka:8761/eureka
    env_file:
      - secrets-db-app.env
    expose:
      - "8181"
    networks:
      - appnet
    depends_on:
      - db
      - eureka
  verses:
    image: li/verses-server:latest
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - LYRICAL_MYSQL_URI=jdbc:mariadb://db:3306/lyrical
      - EUREKA_URI=http://eureka:8761/eureka
    env_file:
      - secrets-db-app.env
    expose:
      - "8282"
    networks:
      - appnet
    depends_on:
      - db
      - eureka
  impacted:
    image: li/impacted-server:latest
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - LYRICAL_MYSQL_URI=jdbc:mariadb://db:3306/lyrical
      - EUREKA_URI=http://eureka:8761/eureka
    env_file:
      - secrets-db-app.env
    expose:
      - "8383"
    networks:
      - appnet
    depends_on:
      - db
      - eureka
  lookup:
    image: li/lookup-server:latest
    mem_limit: 256m
    mem_reservation: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - EUREKA_URI=http://eureka:8761/eureka
    expose:
      - "8484"
    networks:
      - appnet
    depends_on:
      - eureka
  eureka:
    image: li/eureka:latest
    mem_limit: 256m
    mem_reservation: 256m
    expose:
      - "8761"
#    ports:
#      - "8761:8761"
    networks:
      - appnet
  db:
    image: mariadb:10.5.2
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=lyrical
    env_file:
      - secrets-db.env
    mem_limit: 256m
    mem_reservation: 256m
    expose:
      - "3306"
#    ports:
#      - "3306:3306"
    networks:
      - appnet
  keycloak.net:
    image: jboss/keycloak:9.0.2
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/keycloak-lyrical-realm.json
    env_file:
      - secrets-keycloak.env
    volumes:
      - "./vols/keycloak-lyrical-realm.json:/tmp/keycloak-lyrical-realm.json:ro"
    mem_limit: 512m
    mem_reservation: 512m
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - keycloaknet
networks:
  appnet:
    driver: bridge
  keycloaknet:
    driver: bridge
