apiVersion: v1
kind: Service
metadata:
  name: impacted-service
  labels:
    app: lyrical-impact
spec:
  ports:
    - protocol: TCP
      port: 8383
  selector:
    app: lyrical-impact
    tier: impacted
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: impacted-service
  labels:
    app: lyrical-impact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrical-impact
  template:
    metadata:
      labels:
        app: lyrical-impact
        tier: impacted
    spec:
      containers:
        - name: lyrical-impact-impacted-pod
          image: gcr.io/lyrical-impact/li/impacted-server:2.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: configmap-base
            - configMapRef:
                name: configmap-db-app
            - secretRef:
                name: secret-db-app
          ports:
            - name: http
              containerPort: 8383
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: 8383
